### ISSUE TITLE
Namespace ambiguity issue for filesystem mount point part of metrics

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-collector-df#10]
Due to the fact that the filesystem part of the "df -T -P" output might contain / like the following output coming from my Linux system

```C
Filesystem                Type     1024-blocks      Used Available Capacity Mounted on
udev                      devtmpfs     8113640        12   8113628       1% /dev
tmpfs                     tmpfs        1624944      2524   1622420       1% /run
/dev/dm-3                 ext4       103077152  84200980  13617116      87% /
none                      tmpfs              4         0         4       0% /sys/fs/cgroup
none                      tmpfs           5120         0      5120       0% /run/lock
none                      tmpfs        8124712       280   8124432       1% /run/shm
none                      tmpfs         102400        32    102368       1% /run/user
/dev/mapper/data--vg-data ext4       722343000 319310640 371560244      47% /data
/dev/sda1                 ext4         1998672    393128   1484304      21% /boot
/dev/mapper/vms--vg-vms   ext4       309501952 151700240 142056896      52% /vms
```

The plugin code internally converts these chars into _ using the [following code](https://github.com/intelsdi-x/snap-plugin-collector-df/blob/master/df/plugin.go#L220)

Doing this, there is no way (or at least there does not seem to be at first look) for the user to be able to differentiate between /dir1/part1 and /dir1_part1

**Comment by obourdon** [comment]
After 2nd thought, may be this is a no-brainer issue or even not an issue at all if metrics are moved to dynamic ones as they should most probably be. Please advise

**Comment by obourdon** [comment]
May be another/additional way to solve this is to also send the real filesystem mount point as a separate metric, unchanged

**Comment by marcin-krolik** [comment]
@obourdon What do you think of changing "/" to "::". Double colon should be unique.

**Comment by marcin-krolik** [comment]
@obourdon As for usage of dynamic metrics - I agree we could use it here. Unfortunately it won't fix issue you are reporting. We do need some way to present `NamespaceElement` without "/" characters, otherwise it will break the whole namespace. We won't be able to query for such metrics in task manifest. I think that double colon, could serve here well, much better then "_"

**Comment by obourdon** [comment]
@marcin-krolik I also thought about changing the current _ to anything else but whatever char/chars is/are selected it will still end up in the same problem. The :: you are suggesting might used by Perl modules for instance

This is a generic issue for all REST URI members and even the HTML escaping of / into %2f which we could also envisaged does not work because this escape can be filtered by default Apache configurations therefore leading into other kind of issues if you are accessing snap URIs from behind a  Apache (reverse) proxy for instance. I googled to find a generic REST solution for this without any success so far.

I understand your point and agree that having metrics being dynamic will not solve this either. I have implemented and tried a "fix" which is more a workaround according to [what I suggested here](https://github.com/intelsdi-x/snap-plugin-collector-df/issues/10#issuecomment-227669068) but of course, this requires some additional work on the publisher and/or publish target side to be able to use this new metric

**Comment by obourdon** [comment]
@marcin-krolik may be you could have a look at [my local branch](https://github.com/obourdon/snap-plugin-collector-df/tree/all_in_1) which has several fixes for [docker issue](https://github.com/intelsdi-x/snap-plugin-collector-df/issues/8) as well as implement dynamic metrics and the fix mentioned above. Please feel free to comment/suggest/flame/... & many thanks in advance

**Comment by marcin-krolik** [comment]
@obourdon Good points Oliver. I will take a closer look at your branch tomorrow.

**Comment by obourdon** [comment]
@marcin-krolik thanks for your time

**Comment by marcin-krolik** [comment]
@obourdon I took a look at your branch. Please find my comments below

1 [this condtion](https://github.com/obourdon/snap-plugin-collector-df/blob/all_in_1/df/plugin.go#L269) will be always false. Consider changing to 
```go
if !(len(leftFields) == 6 || len(leftFields) == 7) { //...}
```
2 There's no need to create copy of `ns` like [here](https://github.com/obourdon/snap-plugin-collector-df/blob/all_in_1/df/plugin.go#L130). You may directly work on `ns` variable (slice is reference type). I would also reimplement the main loop to be similar to 
```go
for _, m := range mts {
    ns := m.Namespace()
    if len(ns) < 5 {
        return nil, fmt.Errorf("Wrong namespace length %d", len(ns))
    }
    if ns[len(ns)-2].Value == "*" {
        for _, dfm := range dfms {
            ns[len(ns)-2].Value = dfm.MountPoint
            metric := plugin.MetricType{
                Timestamp_: curTime,
                Namespace_: ns,
            }
            fillMetric(kind, dfm, &metric)
            metrics = append(metrics, metric)     
        }
    } else {
            for _, dfm := range dfms {
                if ns[len(ns)-2].Value == dfm.MountPoint {
                    metric := plugin.MetricType{
                        Timestamp_: curTime,
                        Namespace_: ns,
                    }
                    kind := ns[len(ns)-1].Value
                    fillMetric(kind, dfm, &metric)  
                    metrics = append(metrics, metric)
                }
            }
    }

I think it's more readable.
```
3 Why are you not using `math.Ceil` instead making your own implementation?

Apart from that it looks good in my opinion. It's really great idea to utilize `syscall.Statfs` instead of `df`.

**Comment by obourdon** [comment]
@marcin-krolik thanks a lot for your comments and finding the wrong test conditions :-( I will work on integrating your suggestion in my branch tomorrow.

As far as the math.Ceiling part, I had originally used it however we have had requests to make sure that snap binaries and plugins do not grow wild unnecessarily because GoLang self containess advantage can also be seen as an important drawback for usage in memory constrained environments. Therefore, I have considered using a well known and basic ceiling implementation to go in this direction.
Hope this makes sense, best regards & many thanks again

**Comment by obourdon** [comment]
@marcin-krolik I have looked more closely at your comments this morning:

1. I think my initial test is good (as well as yours of course) because 
`if !(len(leftFields) == 6 || len(leftFields) == 7) { //...}`
should be perfectly equivalent to
`if len(leftFields) != 6 && len(leftFields) != 7 { //...}`
or am I missing something here ?

2. perfectly understood and agree that there is no need to copy original ns into ns1 prior to modifications

3. just for completing my GoLang/Snap best practices knowledge, why are you considering that having the for loop within if-else is more readable than having a for loop with embedded if-else ?

4. the obvious advantages/drawbacks of using sys/stafs instead of using df command are:
  - we need to "re-code" and therefore maintain the logic which came from original df C code
  - df C code runs on all kind of UNIXes flavors (not only Linux) whereas the original df collector plugin code was also working on MacOSX for instance
  - it spares the cost of a fork/exec of an external process within the collector plugin
  - it now supports being run in Docker/containers and collecting metrics either from the container either from the host

5. as far as the gathering of original path un-substituted as a new metric, this has the disadvantage of forcing the user to explicitely request to get this metric in order to use it somehow ...

6. did you look at my comment about why I did not use math.Ceil? what do you think ?

I will retest modified code on my side and submit proper PR if everything goes well

Thanks again and best regards

**Comment by obourdon** [comment]
Ok 2 more things

1. as far as the if-else + for-loop I now understand that I was doing the exact same test within the for-loop therefore your comment is very well justified. I spent too many years lately trusting compiler optimization techniques which are very effective in the Java space ;-). Good catch

2. as far as math.Ceil is concerned I understand that the gain in executable space is not that important (~4k if I computed this properly) which leads to the question: if you use only 1 function from a library (like Ceil from math package here) does the go compiler take the entire math library code or only the parts which are required ? Anyways the ceil code written here is not that big and also offers more security when dividing by 0 or other potential exceptions. Please advise

**Comment by obourdon** [comment]
After more indepth testing, the duplication of ns into ns1 is an absolute must  because else all dynamic metrics will have the same entry (last filesystem found)
[New branch available](https://github.com/obourdon/snap-plugin-collector-df/tree/all_in_1) integrating [this new commit](https://github.com/intelsdi-x/snap-plugin-collector-df/commit/5020ba85e8267351465d2cdef215f86ddc46f9f1)

**Comment by obourdon** [comment]
One alternate solution which I have been testing successfully is to add a field/attribute into [NamespaceElement structure](https://github.com/intelsdi-x/snap/blob/master/core/metric.go#L133:L137), say UnchangedValue of type string. You can have a look into the [corresponding modified snap branch can be found here](https://github.com/obourdon/snap/tree/modified_NamespaceElement/core/metric.go#L137)

This new entry will eventually keep the unmodified value of the filesystem mount point as you can see [in this branch](https://github.com/obourdon/snap-plugin-collector-df/tree/modified_NamespaceElement) which correspond to [this commit](https://github.com/intelsdi-x/snap-plugin-collector-df/commit/3d7fa74ade9875dd1f3e6a6a410bc6f55e274f2f)

**Comment by marcin-krolik** [comment]
@obourdon Please find my comments below.

> 
I think my initial test is good (as well as yours of course) because 
if !(len(leftFields) == 6 || len(leftFields) == 7) { //...}
should be perfectly equivalent to
if len(leftFields) != 6 && len(leftFields) != 7 { //...}
or am I missing something here ?

You are right! I calculated your condition as always `false`, which is obviously wrong. 

>
After more indepth testing, the duplication of ns into ns1 is an absolute must because else all dynamic metrics will have the same entry (last filesystem found)
New branch available integrating this new commit

Again, you're right. Copy is necessary. It seems doing reviews  being jet-lagged is not a good idea ;)

>
as far as math.Ceil is concerned I understand that the gain in executable space is not that important (~4k if I computed this properly) which leads to the question: if you use only 1 function from a library (like Ceil from math package here) does the go compiler take the entire math library code or only the parts which are required ? Anyways the ceil code written here is not that big and also offers more security when dividing by 0 or other potential exceptions. Please advise

Complete golang program links all its imports with main package, so as I understand it, the whole `math` will be included, even if only single function is used. If we're not heavily optimizing I would go with standard lib.

>
the obvious advantages/drawbacks of using sys/stafs instead of using df command are:

I think in this case it's the only choice to make this plugin work in dockerized environment. Great you found it!

>
One alternate solution which I have been testing successfully is to add a field/attribute into NamespaceElement structure, say UnchangedValue of type string. You can have a look into the corresponding modified snap branch can be found here

I think we should avoid introduction of changes to snap framework for single plugin purposes whenever possible. Maybe utilizing metric tags would be helpful here?

**Comment by obourdon** [comment]
I understand your last point and agree with it.

New implementation available in [this updated branch](https://github.com/obourdon/snap-plugin-collector-df/tree/all_in_1)

**Comment by elemoine** [comment]
> I understand your last point and agree with it.

I am personally not convinced :) Using tags for that sounds like a hack to me. It sounds like using tags not for what they are meant to, to work-around a limitation of the framework. And publisher plugins will also need modifications, to somehow be able to interpret those specific tags in a specific manner. The framework doesn't allow namespace element values that include slashes, so it itself should provide some mechanism not to loose the original/real value. This is the framework's responsibility. So extending the framework by adding a `RealValue` field to the `NamespaceElement` structure makes sense to me. It is something that the df plugin will use, and other plugins could use as well.

**Comment by marcin-krolik** [comment]
@elemoine I don't think any changes to publishers/processors would be needed at all. Simply adding tag like `filesystem_real_name` with proper value is enough. Publishers will publish such metrics with this additional tag, which then could be used somewhere outside of snap framework for further processing if needed. As I understand metrics namespace, it is more of unique identifier, then anything else.  I have a feeling that introducing changes to framework to cover some exceptions is not a good way to go. I can bring your idea up to discuss with rest of the snap team, though.

**Comment by jcooklin** [comment]
I think I agree with @elemoine.  In this case the framework should support adding a filesystem path as the value of a `NamespaceElement` (a dynamic metric).

 >The framework doesn't allow namespace element values that include slashes, so it itself should provide some mechanism not to loose the original/real value.

The metrics namespace uniquely identifies the metric  provided on plugin load which populates the metric catalog.  While it's important that the metric provided to the catalog on load (`GetMetricTypes`) does not contain special characters I think we should be able to accept them in the value field on `Collect` which would generically allow the downstream processors and publishers to deal with them.

**Comment by elemoine** [comment]
> @elemoine I don't think any changes to publishers/processors would be needed at all. Simply adding tag like filesystem_real_name with proper value is enough. Publishers will publish such metrics with this additional tag, which then could be used somewhere outside of snap framework for further processing if needed.

Right, but this means two tags when only one is needed, "just" because the Snap framework doesn't allow certain characters in namespace element values. Take the InfluxDB publisher for example. It [converts](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/influx/influx.go#L183-L193) every Snap tag to an InfluxDB tag. So you'll end up with two tags in the series: `filesystem=rootfs` and `filesystem_real_name=/`. This is working around a limitation in the framework.


> As I understand metrics namespace, it is more of unique identifier, then anything else. I have a feeling that introducing changes to framework to cover some exceptions is not a good way to go.

To me this is not an exception, it is a general problem for which a general solution is required :)

**Comment by elemoine** [comment]
> The metrics namespace uniquely identifies the metric provided on plugin load which populates the metric catalog. While it's important that the metric provided to the catalog on load (GetMetricTypes) does not contain special characters I think we should be able to accept them in the value field on Collect which would generically allow the downstream processors and publishers to deal with them.

That makes sense to me.

**Comment by marcin-krolik** [comment]
>
I think we should be able to accept them in the value field on `Collect` which would generically allow the downstream processors and publishers to deal with them.

@jcooklin Just want to understand this correctly. In this particular case we would allow to set `NamespaceElement.Value` to let's say `/dev/sda1`?

**Comment by jcooklin** [comment]
Yes, I feel this should be valid in the collect call. The separator in the
manifest can feasibly be anything. For instance, the namespace could be
described as "%intel%df%/dev/sda1%used". The framework would peak the first
character to determine the namespace separator.

What are your thoughts?

**Comment by obourdon** [comment]
@jcooklin I agree with your proposal. However I think that due to the potential deep impacts on other parts of the code and framework global behaviour, these changes should be done by snap deep knowledgeable people. May be also this issue should be moved/duplicated into to snap framework itself. Please advise.

**Comment by obourdon** [comment]
Please note that this issue is also valid for the snap-plugin-collector-swap pluggin:

See usage of [this method](https://github.com/intelsdi-x/snap-plugin-collector-swap/blob/master/swap/swap.go#L478:L480) at line [249](https://github.com/intelsdi-x/snap-plugin-collector-swap/blob/master/swap/swap.go#L249) and  [306](https://github.com/intelsdi-x/snap-plugin-collector-swap/blob/master/swap/swap.go#L306)

**Comment by obourdon** [comment]
@jcooklin sorry but looking back at your proposal more in depth and knowing that all of these metrics are now completely dynamic, may be we have a bit of misunderstanding here

If we want to query metrics for a specific filesystem, I still think that what you propose here might be valid. However when querying all dynamic metrics at once is not (and was not) an issue because of using the wildcard notation like

`/intel/procfs/filesystem/*/space_free`
or
`/intel/procfs/filesystem/*/*`

what does not seem to be possible is, when receiving the metrics back once collected, to be able to retrieve the proper name of the originated filesystem whether using / or any other separator because this FS can contain (almost) any char (including / % # , ...)

To take a complete use case, let's assume I am collecting FS metrics only that I published via heka publisher into an Heka/Hindsight instance which will in turn store everything into InfluxDB with using dimensions:
This means that:
`/intel/procfs/filesystem/FS1/space_free`
will become a measurement with name 
`intel.procfs.filesystem.space_free`
and FS1 as a tag and for this I need FS1 to be the original value as displayed on the host aka
`/var/log` or `/tmp/123%456` or anything like this
How would this be achievable ?
If there is something I misunderstood or overlooked please tell me.

**Comment by jcooklin** [comment]
@obourdon it would be achieved by "correctly" stringifying the namespace which will involve inspecting the namespace elements to identify what separator should be used (`/` being the default).  @marcin-krolik describes using a priority list in the RFC on this topic https://github.com/intelsdi-x/snap/issues/1234.  If after looping through the namespace elements and finding a `/` was used anywhere the next available separator would presumably be tested and so on.
