### ISSUE TITLE
TravisCI does not trigger on this repository

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-collector-df#12]
even though repository contains .travis.yml file

**Comment by IzabellaRaulin** [comment]
Thanks @obourdon for notice that. Travis service was disabled for this repo. Now it is in enabled state. I also prepared mock pull request to verify that it works properly (https://github.com/intelsdi-x/snap-plugin-collector-df/pull/14)

I suppose that this issue can be closed.

**Comment by obourdon** [comment]
@IzabellaRaulin thanks for fixing this
