### ISSUE TITLE
Plugin is not compatible with Docker

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-df#8]
The df plugin is based on the `df` Unix command. When executed in a Docker container the `df` command obviously reports about the file systems mounted into the container. Instead, the user probably expects that the df plugin collect free space metrics for the host file systems. But we cannot make `df` read sys and proc information from other paths than `/proc` and `/sys`, so maybe using the `df` plugin makes no sense when snapd is executed in a Docker container. In that case we could just add a note the plugin README mentioning that the plugin is not compatible with Docker.

**Comment by obourdon** [comment]
I have a basic working version in [this local branch](https://github.com/obourdon/snap-plugin-collector-df/tree/no_df_command_only_procfs)

However, as I have modified the signature of the collect() interface, test do not pass for obvious reasons. Right now I guess this is not the proper/best way to pass the procPath string parameter to the collect method but I am not up to speed/fluent enough with go interfaces, tests and others to solve this quickly.

Can someone help me here please ?
Many thanks

**Comment by obourdon** [comment]
@tiffanyfj can you please look at [my new branch](https://github.com/obourdon/snap-plugin-collector-df/tree/all_in_1) and tell me what you think in general but more precisely on the change of signature mentioned in my previous comment above in this discussion which prevents the tests from passing successfully. Thanks

**Comment by obourdon** [comment]
@intelsdi-x/snap-maintainers can someone please have a look at [my branch](https://github.com/obourdon/snap-plugin-collector-df/tree/all_in_1) and tell me how to modify it properly so has to properly pass the procPath string. Thanks
